save_dir: /home/Dengqy/checkpoints/ccl
load_path: /home/Dengqy/checkpoints/ccl/ccl_flexmatch_cifar100_100_seed2/checkpoint.pth.tar
data_dir: /home/pc/utils/dataset
save_name: ccl_flexmatch_cifar100_100_seed2
dist_url: tcp://127.0.0.1:35021
dataset: cifar100
num_labels: 100
num_classes: 100
seed: 2
k: 0.7
resume: True
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 1024
batch_size: 64
eval_batch_size: 1024
hard_label: True
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.001
amp: False
net: WideResNet_Proj
net_from_name: False
depth: 28
widen_factor: 8
leaky_slope: 0.1
proj: True
dropout: 0.0
train_sampler: RandomSampler
num_workers: 1
alg: ccl
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_backend: nccl
gpu: None
