tags: cssc_fixmatch_stl10_80_seed0
#save_dir: /home/Dengqy/checkpoints/cssc
#load_path: /home/Dengqy/checkpoints/cssc/cssc_fixmatch_stl10_80_seed0/checkpoint.pth.tar
#data_dir: /home/pc/utils/dataset
#save_dir: /mnt/Dengqy/checkpoints/cssc
#load_path: /mnt/Dengqy/checkpoints/cssc/cssc_fixmatch_stl10_80_seed0/checkpoint.pth.tar
#data_dir: /mnt/pc/utils/dataset
#save_dir: /home/chenjian/Yanghm/checkpoints/cssc
#load_path: /home/chenjian/Yanghm/checkpoints/cssc/cssc_fixmatch_stl10_80_seed0/checkpoint.pth.tar
#data_dir: /home/chenjian/Yanghm/datasets
save_dir: /BS/yong_project1/work/qinyi/checkpoints/cssc
load_path: /BS/yong_project1/work/qinyi/checkpoints/cssc/cssc_fixmatch_stl10_80_seed0/checkpoint.pth.tar
data_dir: /BS/yong_project1/work/qinyi/dataset
save_name: cssc_fixmatch_stl10_80_seed0
dist_url: tcp://127.0.0.1:34002
dataset: stl10
num_labels: 80
num_classes: 10
p_cutoff: 0.95
seed: 0
k: 7
resume: True
overwrite: True
use_tensorboard: True
epoch: 1
num_train_iter: 1048576
num_eval_iter: 1024
batch_size: 64
eval_batch_size: 1024
hard_label: True
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: WideResNetVar_Proj
net_from_name: False
depth: 28
widen_factor: 2
leaky_slope: 0.1
proj: True
dropout: 0.0
train_sampler: RandomSampler
num_workers: 1
alg: cssc
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_backend: nccl
gpu: 0
